// Generated by gencpp from file quori_interactions/ArmsCmd.msg
// DO NOT EDIT!


#ifndef QUORI_INTERACTIONS_MESSAGE_ARMSCMD_H
#define QUORI_INTERACTIONS_MESSAGE_ARMSCMD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace quori_interactions
{
template <class ContainerAllocator>
struct ArmsCmd_
{
  typedef ArmsCmd_<ContainerAllocator> Type;

  ArmsCmd_()
    : r_shoulder_pitch(0.0)
    , r_shoulder_roll(0.0)
    , l_shoulder_pitch(0.0)
    , l_shoulder_roll(0.0)
    , waist_pitch(0.0)  {
    }
  ArmsCmd_(const ContainerAllocator& _alloc)
    : r_shoulder_pitch(0.0)
    , r_shoulder_roll(0.0)
    , l_shoulder_pitch(0.0)
    , l_shoulder_roll(0.0)
    , waist_pitch(0.0)  {
  (void)_alloc;
    }



   typedef float _r_shoulder_pitch_type;
  _r_shoulder_pitch_type r_shoulder_pitch;

   typedef float _r_shoulder_roll_type;
  _r_shoulder_roll_type r_shoulder_roll;

   typedef float _l_shoulder_pitch_type;
  _l_shoulder_pitch_type l_shoulder_pitch;

   typedef float _l_shoulder_roll_type;
  _l_shoulder_roll_type l_shoulder_roll;

   typedef float _waist_pitch_type;
  _waist_pitch_type waist_pitch;





  typedef boost::shared_ptr< ::quori_interactions::ArmsCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::quori_interactions::ArmsCmd_<ContainerAllocator> const> ConstPtr;

}; // struct ArmsCmd_

typedef ::quori_interactions::ArmsCmd_<std::allocator<void> > ArmsCmd;

typedef boost::shared_ptr< ::quori_interactions::ArmsCmd > ArmsCmdPtr;
typedef boost::shared_ptr< ::quori_interactions::ArmsCmd const> ArmsCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::quori_interactions::ArmsCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::quori_interactions::ArmsCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::quori_interactions::ArmsCmd_<ContainerAllocator1> & lhs, const ::quori_interactions::ArmsCmd_<ContainerAllocator2> & rhs)
{
  return lhs.r_shoulder_pitch == rhs.r_shoulder_pitch &&
    lhs.r_shoulder_roll == rhs.r_shoulder_roll &&
    lhs.l_shoulder_pitch == rhs.l_shoulder_pitch &&
    lhs.l_shoulder_roll == rhs.l_shoulder_roll &&
    lhs.waist_pitch == rhs.waist_pitch;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::quori_interactions::ArmsCmd_<ContainerAllocator1> & lhs, const ::quori_interactions::ArmsCmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace quori_interactions

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::quori_interactions::ArmsCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::quori_interactions::ArmsCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quori_interactions::ArmsCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quori_interactions::ArmsCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quori_interactions::ArmsCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quori_interactions::ArmsCmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::quori_interactions::ArmsCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "18963acf222a3961918de358f517947a";
  }

  static const char* value(const ::quori_interactions::ArmsCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x18963acf222a3961ULL;
  static const uint64_t static_value2 = 0x918de358f517947aULL;
};

template<class ContainerAllocator>
struct DataType< ::quori_interactions::ArmsCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "quori_interactions/ArmsCmd";
  }

  static const char* value(const ::quori_interactions::ArmsCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::quori_interactions::ArmsCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 r_shoulder_pitch\n"
"float32 r_shoulder_roll\n"
"float32 l_shoulder_pitch\n"
"float32 l_shoulder_roll\n"
"float32 waist_pitch\n"
;
  }

  static const char* value(const ::quori_interactions::ArmsCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::quori_interactions::ArmsCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.r_shoulder_pitch);
      stream.next(m.r_shoulder_roll);
      stream.next(m.l_shoulder_pitch);
      stream.next(m.l_shoulder_roll);
      stream.next(m.waist_pitch);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArmsCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::quori_interactions::ArmsCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::quori_interactions::ArmsCmd_<ContainerAllocator>& v)
  {
    s << indent << "r_shoulder_pitch: ";
    Printer<float>::stream(s, indent + "  ", v.r_shoulder_pitch);
    s << indent << "r_shoulder_roll: ";
    Printer<float>::stream(s, indent + "  ", v.r_shoulder_roll);
    s << indent << "l_shoulder_pitch: ";
    Printer<float>::stream(s, indent + "  ", v.l_shoulder_pitch);
    s << indent << "l_shoulder_roll: ";
    Printer<float>::stream(s, indent + "  ", v.l_shoulder_roll);
    s << indent << "waist_pitch: ";
    Printer<float>::stream(s, indent + "  ", v.waist_pitch);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QUORI_INTERACTIONS_MESSAGE_ARMSCMD_H
