// Generated by gencpp from file quori_gui/Opcmd.msg
// DO NOT EDIT!


#ifndef QUORI_GUI_MESSAGE_OPCMD_H
#define QUORI_GUI_MESSAGE_OPCMD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace quori_gui
{
template <class ContainerAllocator>
struct Opcmd_
{
  typedef Opcmd_<ContainerAllocator> Type;

  Opcmd_()
    : data()
    , angle_dist(0.0)  {
    }
  Opcmd_(const ContainerAllocator& _alloc)
    : data(_alloc)
    , angle_dist(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _data_type;
  _data_type data;

   typedef double _angle_dist_type;
  _angle_dist_type angle_dist;





  typedef boost::shared_ptr< ::quori_gui::Opcmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::quori_gui::Opcmd_<ContainerAllocator> const> ConstPtr;

}; // struct Opcmd_

typedef ::quori_gui::Opcmd_<std::allocator<void> > Opcmd;

typedef boost::shared_ptr< ::quori_gui::Opcmd > OpcmdPtr;
typedef boost::shared_ptr< ::quori_gui::Opcmd const> OpcmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::quori_gui::Opcmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::quori_gui::Opcmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::quori_gui::Opcmd_<ContainerAllocator1> & lhs, const ::quori_gui::Opcmd_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data &&
    lhs.angle_dist == rhs.angle_dist;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::quori_gui::Opcmd_<ContainerAllocator1> & lhs, const ::quori_gui::Opcmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace quori_gui

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::quori_gui::Opcmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::quori_gui::Opcmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quori_gui::Opcmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quori_gui::Opcmd_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quori_gui::Opcmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quori_gui::Opcmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::quori_gui::Opcmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8e95fd03b16cd7241921e03a50a02cad";
  }

  static const char* value(const ::quori_gui::Opcmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8e95fd03b16cd724ULL;
  static const uint64_t static_value2 = 0x1921e03a50a02cadULL;
};

template<class ContainerAllocator>
struct DataType< ::quori_gui::Opcmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "quori_gui/Opcmd";
  }

  static const char* value(const ::quori_gui::Opcmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::quori_gui::Opcmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string data\n"
"float64 angle_dist\n"
;
  }

  static const char* value(const ::quori_gui::Opcmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::quori_gui::Opcmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
      stream.next(m.angle_dist);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Opcmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::quori_gui::Opcmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::quori_gui::Opcmd_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.data);
    s << indent << "angle_dist: ";
    Printer<double>::stream(s, indent + "  ", v.angle_dist);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QUORI_GUI_MESSAGE_OPCMD_H
